### ISSUE TITLE
smaller input data file

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-lhcb-d2pimumu#1]
The input data file is ~19 GB which is large for comfortable development.

It would be great to produce a smaller file, say read the big one and take every 100th event and write the smaller one that we could use to ease the development.

@atrisovic Can you please look at that?

**Comment by tiborsimko** [comment]
Thanks!  Still it runs "forever" in my modest 8 GB RAM laptop... I stopped it after 4 hours I think.  Could you make it even smaller?

**Comment by atrisovic** [comment]
Hi, yes, I created a new file called `test_D2PimumuOS.root` of only 100KB in the same repository.

**Comment by tiborsimko** [comment]
Thanks, closing. We have a ~1G and a ~10G input file that are now sufficient for further testing. A box with 16G of RAM recommended to run Optimise.
